### ISSUE TITLE
Migrating to Sirius 3.1

### ISSUE THREAD

**Issue by philippemerle** [occiware/ecore#10]

**Comment by wpiers** [comment]
by commit https://github.com/occiware/ecore/commit/3856c8449b0990f606b632cddd7480020d17f5d8

To upgrade dev IDE, use eclipse Help > Install New Software dialog, then fill the form like in the attached picture: 
![maj_sirius](https://cloud.githubusercontent.com/assets/1905213/10913528/9c2130d2-824e-11e5-8caa-04f7944ab352.PNG)
