### ISSUE TITLE
Docker Studio - connector fails when having only clicked in Volumes prop

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#112]
Cause : merely clicking in the Volumes prop's value field in the Properties view creates a new empty Volumes property, which is parsed has being a Volume with an empty name, see log :

```
14:45:06.077 [main] DEBUG c.g.d.jaxrs.DockerCmdExecFactoryImpl - 5 * Sending client request on thread main
5 > POST https://192.168.99.100:2376/v1.20/containers/create?name=ozwillo-mongo-1
5 > Accept: application/json
5 > Content-Type: application/json
{"name":"ozwillo-mongo-1","Image":"ozwillo-mongo-1","Volumes":{"":{}},"ExposedPorts":{},"HostConfig":{}} 
```

Solution : patch parsing. BEWARE, maybe it happens with other props (all, or only complex ones ?) in the Docker Studio or in other Studios ; in which case a generic solution would be better.

This problem is not big, but it can very easily mess up configurations that had been working only a moment ago and make spend some time before finding the cause, and then the .occic XML has to be hacked or the container recreated.

**Comment by fifiant** [comment]
I am not able to reproduce this problem. can you give me more details?
