### ISSUE TITLE
Docker Studio - allow copy / pasting inside Containers

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#113]
Copy / pasting would be very useful, for instance copy / pasting mongo containers when creating a mongodb replica set in a single machine for demo purpose, or copy / pasting machines with mongo containers when creating a distributed production-like mongodb replica set.

BEWARE maybe this issue should affect ALL Studios, and a generic solution can be provided.

Ideally, there should be a warning until the copy's name has been changed (and then the Hostname etc. should be recomputed accordingly).

Maybe (outgoing ?) links could also be copied.

And 2. it works for VMs BUT all links originate from the source ather than the copy.

Could it even be done generically for all designers in the designer generator ?

**Comment by cgourdin** [comment]
Issue added on docker studio v2.
