### ISSUE TITLE
Docker Studio - Set hostname to Hostname (and Hostname to a nice version of Name)

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#116]
It seems that ping hostname does not work even inside the container, and docker inspect doesn't show that hostname has been configured:

```
12:01:01.407 [main] DEBUG org.apache.http.headers - http-outgoing-143 >> POST /v1.20/containers/create?name=ozwillo-datacore-1 HTTP/1.1
{"name":"ozwillo-datacore-1","Image":"mdutoo/ozwillo-datacore","Volumes":{},"ExposedPorts":{},"HostConfig":{"PortBindings":{"8080/tcp":[{"HostIp":"","HostPort":"8080"}]}}}
```

Unless I'm mistaken both should have been.

Additionally, using Name to init Hostname would be helpful.

**Comment by fifiant** [comment]
This issue is fixed.

**Comment by mdutoo** [comment]
Great, thanks !
And are there other docker params that are not filled from the model ?

**Comment by fifiant** [comment]
All the param that Dokcer-Java API allows is taken into account.
