### ISSUE TITLE
docker studio - allow to refactor a vm in another kind

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#124]
VMs can be copy / pasted but this doesn't change their kind.
It would be very useful to copy / paste a vm to another kind of vm, or (which has the same output) allow to refactor a vm in another kind, ex. from VirtualBox to OpenStack.

**Comment by mdutoo** [comment]
Or rather use mixins to extend Compute, like the IPNetworkInterface mixin can be applied to the NetworkInterface Resource.

**Comment by barais** [comment]
Can be defined using EWL and can be called in SIRIUS editor
https://github.com/occiware/EWLSiriusIntegration


an example is provided in example folder.
