### ISSUE TITLE
all studios - allow to refactor a resource in another "sibling" kind

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#125]
See practical example at  #124.

Refactoring allows to easily create whole new configurations by derivation of existing ones and is therefore very useful, ex. to create a production configuration from a test / dev configuration (Eclipse Con demo), or to easily explore the opportunity of migrating VMs to ex. Scalair or Amazon AWS and compare the refactored configuration to the original thanks to the T3.6 Decision Making tool.

Such refactoring accelerators would be very useful in all studios.

2 solutions:
- provide to users the ability to script refactorings, ex. using [Epsilon Wizard Language](https://www.eclipse.org/epsilon/doc/ewl/) (also allows to provide parameters) which could be integrated in Sirius (@wpiers ?)
- for very useful use cases (ex. between VMs), code them specifically in the Studios

**Comment by mdutoo** [comment]
Or rather use mixins, like the IPNetworkInterface mixin can be applied to the NetworkInterface Resource.

**Comment by barais** [comment]
Can be defined using EWL and can be called in SIRIUS editor

https://github.com/occiware/EWLSiriusIntegration

**Comment by vincent-zurczak** [comment]
I don't know if it was relevant to close this issue (yet).

Sure, EWLSiriusIntegration seems to bring what is necessary for refactoring. But IMO, this plug-in should be installed by default in the studio. It is a real effort for users to install additional plug-ins, no matter the efforts brought to ease their installation.

The refactoring feature is too important to be delivered separately. :sweat_smile:

**Comment by barais** [comment]
Ok I will reopen the issue and package it also in the studio. 

I will also try to write some business refactoring

Regards

**Comment by philippemerle** [comment]
Hi Olivier, changing the OCCI scheme of an extension can be a general-purpose refactoring action.
It needs to change the scheme attribute of the root Extension object
then change the scheme of each Kind and Mixin children of the extension
then change the scheme of each Action object.
So this is really a complex/advanced refactoring, but useful when we want to update the scheme of an extension, eg from http://occiware to http://ogf. Moreover this refactoring requires a parameter: the new scheme.

**Comment by barais** [comment]
Ok I will try to do an example with that. 

The parameter is not an issue. Even in my simple renaming example. The new names are inputs from the user

**Comment by barais** [comment]
Sorry the 3G connexion is horrible, you can find an initial solution here. 

https://github.com/occiware/EWLSiriusIntegration/blob/master/example/ChangingScheme.ewl
