### ISSUE TITLE
Allow to configure exposed ports on VirtualBox (and other attributes, on other Compute kinds)

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#132]
Otherwise web / API servers or Docker containers (such as the Ozwillo Datacore in the LinkedData demo) within the VM can't be used (ex. can't be accessed from the host's web browser). Configuring other specific VirtualBox, OpenStack... attributes is probably also useful for the same reason.

Workaround: configure them in the VirtualBox UI.

**Comment by fifiant** [comment]
In the current Docker model there is no way to expose port at VM level. However, This operation is easily done at Container level.

**Comment by mdutoo** [comment]
You are right, this is not a Docker matter, and it is easily done at ex. VirtualBox level.

However, while I acknowledge it is low priority, it would still be very useful since it is done almost every time Virtual Box is used in the Studio, and there are a number of ways of doing it: http://stackoverflow.com/questions/32174560/port-forwarding-in-docker-machine .

**Comment by cgourdin** [comment]
Transfered in docker studio v2 issues : https://github.com/occiware/Docker-Studio/issues/33
