### ISSUE TITLE
Docker Studio - Compute state inconsistencies

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#136]
When opening a model whose Computes were started (green) last time but have since been stopped (because of a crash or manual stop):
- neither the VMs nor the Docker containers' states are synchronized i.e. they are still green
- doing startAll on the VM starts only the VM but not its Docker containers
- however the Docker containers can be started using their Restart (or Stop then Start) actions

**Comment by fifiant** [comment]
It is normal, when you leave the studio you should necessary save the state.

**Comment by philippemerle** [comment]
Docker Studio provides an action to synchronize the model from the environment.
This action introspects the Docker machines and containers and then update the model accordingly.
