### ISSUE TITLE
Migrating to Docker 1.9

### ISSUE THREAD

**Issue by philippemerle** [occiware/ecore#16]
Docker 1.9 offers a new feature to manage Docker Network allowing to create private networks and connect containers to networks.

**Comment by barais** [comment]
Yes et c'est très cool
http://blog.docker.com/2015/11/docker-multi-host-networking-ga/

Olivier

2015-11-04 16:17 GMT+01:00 philippemerle <notifications@github.com>:

**Comment by philippemerle** [comment]
Yep, Docker 1.9 seems to be cool.
Steps to implement:
1) update the OCCIware Docker Extension to include the concept of Docker Network (extends Infrastructure Network)
2) regenerate Docker.ecore and Java EMF code.
3) update Docker Designer to allow to create Docker Network and Infrastructure NetworkInterface
4) update Docker generator to take Docker Network into account
5) create a new Docker configuration with a Machine containing a Network and several containers
6) test/correct until this works.

We will extend the  to

**Comment by fifiant** [comment]
The current version of Docker is 1.11.2.

The multi-host-network is also supported. Hoverver, we this version od Docker '1.11.2' we need to start a container which runs as key/value storage.
