### ISSUE TITLE
Cloud Designer User's Guide

### ISSUE THREAD

**Issue by philippemerle** [occiware/ecore#17]
Need to produce the Cloud Designer User's Guide.
This guide will present how users ould use all the features of Cloud Designer:
- Create a new OCCI extension
- Create a new OCCI configuration
- OCCI Designer
- OCCI Editor
- Textile documentation generator
- XML erocci generator
- Curl-based script generator
- Docker Designer
- Docker scripts generator
- etc.

**Comment by wpiers** [comment]
The tutorial is available here : https://github.com/occiware/ecore/blob/master/clouddesigner/org.occiware.clouddesigner.doc/user_guide.md

There is already a quite large docker designer doc here: https://github.com/occiware/ecore/blob/master/clouddesigner/org.occiware.clouddesigner.occi.docker.connector/README.md

**Comment by vincent-zurczak** [comment]
Partially achieved with occiware/occiware.github.io#3
See http://occiware.github.io/content/user-guides/snapshot/index.html and http://occiware.github.io/content/developer-guides/snapshot/index.html

IMO, this issue should be closed.
Issues related to the documentation should be managed in the [occiware.github.io](https://github.com/occiware/occiware.github.io) repository.

**Comment by wpiers** [comment]
+1

**Comment by wpiers** [comment]
And thanks a lot for your work !
