### ISSUE TITLE
Docker connector kills erocci because has boolean attributes

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#173]
Docker connector kills erocci when used through erocci-dbus-java:

=ERROR REPORT==== 7-Oct-2016::17:34:36 ===
[line 36] parse error: {xml, <<"Unexpected error: badarg">>}

The cause is that the Docker OCCI extension has boolean attributes (ex. "privileged"), which are not supported by erocci, just as said in erocci/erocci#85 . Workaround is to [rather use Enums][http://occiware.github.io/content/user-guides/snapshot/howtos.html), upgrade erocci or not use it just the same.

**Comment by cgourdin** [comment]
Could you try this with MART server ? I didn't try boolean attribute value on json files on my test sessions. If it's not working i'll made an upgrade.
In your json representation file, do you have a field like this : 
"privileged": true   ==> this is a boolean
Or like this : 
"privileged": "true"  ==> this is a string

**Comment by fifiant** [comment]
@mdutoo the corrections provided by @cgourdin fix your problem ?
