### ISSUE TITLE
Cloud Designer Developer's Guide

### ISSUE THREAD

**Issue by philippemerle** [occiware/ecore#18]
Need to produce the Cloud Designer Developer's Guide.
This guide will present how developers could extend Cloud Designer:
- Create a new OCCI extension specific Designer
- Develop a new generator 
- Develop a new connector
- etc.

**Comment by wpiers** [comment]
https://github.com/occiware/ecore/blob/master/clouddesigner/org.occiware.clouddesigner.doc/developer_guide.md

placeholder

**Comment by vincent-zurczak** [comment]
Partially achieved with occiware/occiware.github.io#3
See http://occiware.github.io/content/user-guides/snapshot/index.html and http://occiware.github.io/content/developer-guides/snapshot/index.html

IMO, this issue should be closed.
Issues related to the documentation should be managed in the [occiware.github.io](https://github.com/occiware/occiware.github.io) repository.

**Comment by wpiers** [comment]
+1
