### ISSUE TITLE
Docker Studio now does "docker create" with "sleep" command which overwrites regular CMD

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#184]
which forbids ex. my mongo to start in https://github.com/occiware/occiware-ozwillo/blob/master/connector-analytics/docker/ozwillo-mongo/Dockerfile .

Maybe it's better to use ENTRYPOINT in Dockerfile to start apps, but CMD uniquely allows to be overriden, and other people use it also, ex. https://github.com/docker-library/tomcat/blob/9ef39e44020d9ac03c8c15bae5e5b0ba96faa128/7/jre8/Dockerfile

example Studio log:

08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> POST /v1.23/containers/create?name=ozwillo-ozenergy-1 HTTP/1.1
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> Accept: application/json
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> Content-Type: application/json
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> User-Agent: Jersey/2.23.1 (Apache HttpClient 4.5)
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> Transfer-Encoding: chunked
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> Host: 192.168.99.100:2376
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> Connection: Keep-Alive
08:31:58.452 [main] DEBUG org.apache.http.headers - http-outgoing-128 >> Accept-Encoding: gzip,deflate
08:31:58.453 [main] DEBUG c.g.d.j.JerseyDockerCmdExecFactory - 48 * Sending client request on thread main
48 > POST https://192.168.99.100:2376/v1.23/containers/create?name=ozwillo-ozenergy-1
48 > Accept: application/json
48 > Content-Type: application/json
{"name":"ozwillo-ozenergy-1","Hostname":"ozwillo-ozenergy-1","Cmd":["sleep","9999"],"Image":"mdutoo/ozwillo-ozenergy:1.0","Volumes":{},"ExposedPorts":{},"HostConfig":{}}

**Comment by philippemerle** [comment]
The log is not related to any Java package of the OCCIware Studio.
Is this issue really related to the OCCIware Studio?
