### ISSUE TITLE
Docker Studio : copy / paste is broken

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#186]
Copy / pasting one VM with several containers having links between them creates the corresponding VM and containers resources, but with the following problems:
- pasted containers are exactly the same, therefore modifying (or deleting !) copies also modify (or delete) the originals. Emptying the container IDs does not solve it, I guess they are saved somewhere else.
- links between copied containers are wrongly copied as links between originals and copies.

Together, this makes it very easy to break a Docker configuration and delete its containers without warning until it's too late.

NB. about copy / paste, there is also #113 .

**Comment by cgourdin** [comment]
Transfered in https://github.com/occiware/Docker-Studio/issues/27
