### ISSUE TITLE
[Cloud designer]Add a way to manage ui like dialog box, progress bar etc. without coding it in connectors

### ISSUE THREAD

**Issue by cgourdin** [occiware/ecore#188]
The principle is simple, don't do user interface code in connectors. 
The UI is managed by Cloud designer, but there is a lack of some simple ui principles when launching an action or a long task, and when executing operations on connector runtime like :
- Show a dialog box before deleting a resource
- Show a progress bar when long task are launch, this give a state of the progression task in real time and avoid locked screen
It's not delegated to connectors to manage this. See #187 for further examples.

**Comment by philippemerle** [comment]
In a Sirius-based designer it is possible to program what it is do when selecting a menu item. So "Show a dialog box before deleting a resource" can be directly programmed in the Infrastructure designer.

The second case related to progression in the execution of an action requires to provide an API (aka interface ProgressLogging { void progress(String msg); } ) and a singleton for this API. In designers, the singleton will delegate to a current dialog. In MartServer, the singleton will nothing (or log progression messages).

**Comment by cgourdin** [comment]
Transfered in docker studio v2 issues : https://github.com/occiware/Docker-Studio/issues/32
