### ISSUE TITLE
Docker Studio - clean ContainerLinks of deleted containers

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#194]
else NPE in synchronize() when stopping containers:

index 0dca939..bc588b1 100644
--- a/clouddesigner/org.occiware.clouddesigner.occi.docker.connector/src/org/occiware/clouddesigner/occi/docker/connector/DockerConnector.xtend
+++ b/clouddesigner/org.occiware.clouddesigner.occi.docker.connector/src/org/occiware/clouddesigner/occi/docker/connector/DockerConnector.xtend
@@ -1725,7 +1725,8 @@ abstract class MachineManager extends ComputeStateMachine<Machine> {
                        if (compute.links.size > 0) {
 
                                // Stop the containers 
-                               compute.links.forEach[elt|(elt.target as ExecutableContainer).stop(StopMethod.GRACEFUL)]
+                               compute.links.filter[elt|elt.target != null] // else NPE
+                                       .forEach[elt|(elt.target as ExecutableContainer).stop(StopMethod.GRACEFUL)]
 
                        }
                }

**Comment by cgourdin** [comment]
null checks are done in docker studio v2.
