### ISSUE TITLE
Docker Studio - action-wide cache of docker state

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#195]
In 0ed0d0086da8f3ce85bd3f33bc1dba9a2cfe4533 (see #193) I've already explictly cached the list of Docker containers once retrieved, in order to avoid having one docker-machine call per container in startAll and synchronize.

But a better architecture would be to let DockerMachine/ContainerManager to implement interfaces, and to wrap their actual implementation in an implicit request/action-wide cache, in an as much as possible standard (cache JSR) and automated (aspect-like defined, rather than explicitly coded wrapper) way.

Note that it wouldn't improve performance upon 0ed0d0086da8f3ce85bd3f33bc1dba9a2cfe4533 , which is only twice faster than before, since it still does one "docker start" command per container. The only way to be faster would be to do a single, multi-container "docker start" (if it exists ?).

**Comment by cgourdin** [comment]
Done with startall command in docker studio v2.
