### ISSUE TITLE
DockerStudio - remove XTend

### ISSUE THREAD

**Issue by mdutoo** [occiware/ecore#197]
When developing the DockerStudio, XTend generates trace files as soon that more than a few words are written, even within the same line, even without saving the file (which, or at least interacting with the filesystem at this step, is contrary to Eclipse builder concept philosophy). This takes up 300% CPU on my 4 core-machine and freezes Eclipse for more or less 10 seconds.

Solution: an intermediary solution is to find a way to configure XTend to improve that (ex. not to generate trace files). But nothing will be faster than removing XTend and rewriting the Docker connector in Java.

Note that XTend had been chosen 1. for its support of AOP and 2. productivity (such as lambda). But today, AOP has not been used and Java 8 has reached a similar level of productivity. So there is no reason anymore to cling to XTend.

**Comment by cgourdin** [comment]
Xtend is totally removed in docker studio project (v2)
