### ISSUE TITLE
Docker Studio - Commands not working on windows

### ISSUE THREAD

**Issue by wpiers** [occiware/ecore#202]
In /org.occiware.clouddesigner.occi.docker.connector/src/org/occiware/clouddesigner/occi/docker/connector/dockermachine/util/ProcessManager.xtend
The following condition does not work.
} else if(OS.equalsIgnoreCase("win")){
				env = #["cmd", "/c", command]
I workaround the issue by directly executing "command" but I don't know if this is the best solution.

I tested using a local installation of docker machine.

**Comment by cgourdin** [comment]
Issue created on docker studio project.
