### ISSUE TITLE
Docker Studio : performance issues due to property view

### ISSUE THREAD

**Issue by Xia0ben** [occiware/ecore#208]
Beside XTend, I have remarked that the latency issues when using the Docker Studio, it is much slower when the property view is open. My two cents about that is:
- The properties view displays all properties of the currently selected object
- However, the requests to get these properties are slow AND apparently not multi-threaded
- Therefore, at any time you click on an object, it reloads all properties
- Making the whole thing slower when using it overall.

**Comment by cgourdin** [comment]
Fixed on docker-studio project
