### ISSUE TITLE
Cloud Modeler

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#27]
Hi @wpiers, I am trying to design the cloud modeler.

Based on my Cloud.odesign file, when I uploaded the metamodels inside my "Cloud configuration", my Cloud.ecore file is  becoming wrong (Machine -> null and Machine_openStack attributes are also null) as shown in the figure bellow:

![conf](http://s14.postimg.org/miugluold/odesign.png)

This is the ecore file generated by the EMF Tool: https://gist.github.com/fifiant/35c9d48a4a7e9fe3a34f

Thank.

**Comment by wpiers** [comment]
I cannot look at the moment, but could you attach the .ecore file to this issue ? Also compare the ecore with an existing one (docker for instance) to check for differences in the way URIs are managed. This might give you the answer for #28 as well

**Comment by fifiant** [comment]
It is done.
