### ISSUE TITLE
Error while I am trying to import metamodels into my .odesign file

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#28]
@wpiers,

This is the error that occurs while I am trying to import the corresponding ecore file inside my .odesign via the metamodels import.

![conf](http://s28.postimg.org/8jaletorx/error.png)

 Any idea ?

**Comment by philippemerle** [comment]
Is this issue resolved?
Can we close it?

**Comment by fifiant** [comment]
Yes, it is done.
