### ISSUE TITLE
Using OCCI schemes instead of referencing .occie files

### ISSUE THREAD

**Issue by philippemerle** [occiware/ecore#30]
Currently, both OCCI extension and configuration XMI files reference .occie files explicitly, e.g.:
     href="platform:/plugin/org.occiware.clouddesigner.occi/model/Core.occie#//..."
This should be replaced by:
     href="http://schemas.ogf.org/occi/core#//..."
Advantages:
* OCCI files will not depend anymore of the location of other OCCI extension files.
* A module containing an OCCI extension could be renamed without breaking all OCCI files referencing this OCCI extension.

**Comment by philippemerle** [comment]
WARNING the namespace of all Ecore packages has been modified.
You should modify the namespaces in header of your .occie, .occic, .hypervisor, .cloud, .docker files:
* http://schemas.ogf.org/occi → http://schemas.ogf.org/occi/core/ecore
* http://schemas.ogf.org/occi/infrastructure → http://schemas.ogf.org/occi/infrastructure/ecore
* http://schemas.ogf.org/occi/hypervisor → http://schemas.ogf.org/occi/hypervisor/ecore
* http://schemas.ogf.org/occi/cloud → http://schemas.ogf.org/occi/cloud/ecore
* http://schemas.ogf.org/occi/docker → http://schemas.ogf.org/occi/docker/ecore
Else you will have loading errors.

**Comment by vincent-zurczak** [comment]
Updating the name spaces works for me.
I met no issue with this upgrade.
