### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by wpiers** [occiware/ecore#33]
We must merge all existing docs into one, here is what could be the structure :
clouddesigner/org.occiware.clouddesigner.doc
	"User guide"
		dl & install studio (https://github.com/occiware/dev-tools/blob/master/eclipse/README.md)
		basic tuto (attached pdf)	
		linkdata tuto (https://github.com/occiware/dev-tools/blob/master/eclipse/README.md)
	"Developer guide"
		acceleo (https://github.com/occiware/dev-tools/blob/master/eclipse/README.md)
		install sources (https://github.com/occiware/dev-tools/blob/master/eclipse/README.md)

clouddesigner/org.occiware.clouddesigner.occi.connector.jocci.doc (https://github.com/occiware/ecore/blob/master/clouddesigner/org.occiware.clouddesigner.occi.connector.jocci/README.md)

Any plugin, like the jocci connector, requiring aspecific doc, might have its own .doc plugin next.

**Comment by wpiers** [comment]
[CloudDesigner_tutorial.pdf](https://github.com/occiware/ecore/files/48560/CloudDesigner_tutorial.pdf)


Add an accurate description of occi2ecore mapping

**Comment by wpiers** [comment]
#17 & #18 describe more accurately the repartition

**Comment by vincent-zurczak** [comment]
Achieved with occiware/occiware.github.io#3
