### ISSUE TITLE
Menu contextual did not appear

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#36]
@wpiers, In my Cloud.odesing I have added a menu context, but when I ran the modeler It not appear ...

This is the file https://gist.github.com/fifiant/35c9d48a4a7e9fe3a34f , what I did wrong ?

**Comment by wpiers** [comment]
http://www.vogella.com/tutorials/EclipsePreferences/article.html

**Comment by fifiant** [comment]
Thank.

**Comment by philippemerle** [comment]
Is this issue resolved?
Can we close it?
