### ISSUE TITLE
XML generation misses attribute types (causing erocci parse error + crash)

### ISSUE THREAD

**Issue by gibello** [occiware/ecore#42]
Considering the definition below in .occie extension:

kind instance extends core.resource {
	title "Instance"
	attribute roboconf.overriddenExports : Map
}
datatype Map : "java.util.HashMap"

The XML generation produces the following element for roboconf.overriddenExports attribute:

<occi:attribute name="roboconf.overriddenExports" immutable="true" use="optional" type="" title=""/>

The type is empty (should it be "Map" ??). If the XML is used as an Erocci schema, it causes a parse error then Erocci crashes.

**Comment by jeanparpaillon** [comment]
There is no 'Map' type in OCCI Core model.

**Comment by gibello** [comment]
So what ? The studio should generate something that does not cause an 
erocci crash (empty types do).

Should it be type="xs:string" when we can't guess the type ? Or is it an 
erocci bug (empty types should be accepted) ??

**Comment by jeanparpaillon** [comment]
I don't think it is a good idea to accept invalid types (empty type is invalid).

By the time we agree on complex basic types in Core model, I would propose to bind them on "xs:string" as a workaround.

For long term solution, we should agree on a definition of complex basic types, which means:
* list them
* decline their respective rendering

For this discussion, it is more appropriate to post on occi-wg mailist

**Comment by philippemerle** [comment]
I patched the generator in order to generate xs:string for basic types.

**Comment by philippemerle** [comment]
Pierre-Yves: wait for the next delivery of Cloud Designer binaries at http://www.obeo.fr/download/occiware/ (should be done before 1 hour) then regenerate Roboconf.xml

**Comment by philippemerle** [comment]
Generated Roboconf.xml file added to https://github.com/occiware/ecore/tree/master/clouddesigner/org.occiware.clouddesigner.occi.roboconf/erocci

**Comment by gibello** [comment]
Fixed, thanks.
