### ISSUE TITLE
OCCI extension (occie) to ecore

### ISSUE THREAD

**Issue by mehdiAhmed** [occiware/ecore#53]
Hello,

After generating OCCI extension (extension.occie) following new -> Cloud Designer -> OCCI extension Project, I don't  have the possibility to generate extension.ecore from extension.occie. Even if I use 
Cloud Designer -> Generate EMF Tooling. 

I'm using Eclipse Mars.1 in Ubuntu 14.04 LTS.

**Comment by philippemerle** [comment]
Hi Mehdi,

I ran the latest cloud designer.
I created an OCCI extension following new -> Cloud Designer -> OCCI extension
I run Cloud Designer -> Generate EMF Tooling.
extension.ecore and extension.genmodel are generated.
I have tested various cases and it always worked.
Expect one case that failed: if the extension has an empty scheme then the generator produces an exception :(

So check that your extension has a scheme, e.g., http://extension#

**Comment by philippemerle** [comment]
Need to add a new OCL constraint checking that scheme are well-formed, e.g., not empty string, well-formed URI, etc.

**Comment by mehdiAhmed** [comment]
Thanks Philippe,

My scheme is not empty. 
`<occi:Extension xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:occi="http://schemas.ogf.org/occi" name="simulation" scheme="http://occiware.org/simulation#">`
And Generate EMF Tooling does not work. Maybe there are a bug in Studio for Linux !

**Comment by philippemerle** [comment]
Hi Mehdi,
I tried to generate Ecore for your simulation.occie then I saw  that this extension violates OCL constraints related to Category.scheme. Then I corrected schemes (see commits https://github.com/occiware/ecore/commit/ce187794bec8df15922220ac0298d36ac40cbac6).
Now I could generate the .ecore for your simulation.occie.
Coud you try too?
