### ISSUE TITLE
[ OCCIE Modeller ] Attribute edition bugs

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/ecore#55]
**Affected version:** Cloud Designer 0.1.0.201602261035

1. Create an OCCI extension.
2. Add a kind and an attribute to this kind (by default, it is called `attribute1: String`).
3. Click the attribute to edit it (example: `name: String`).
4. Type in 'Enter'. The modeler shows `name: String: String`.
5. Try to edit it again and again, you will keep the same label. :cry:   
It is necessary to use the Xtext (or a text) editor to fix it.

**Comment by philippemerle** [comment]
Hi Vincent,
I commited a correction for this issue.
Now, direct edit allows one to change only the name of the attribute, i.e., ': TYPE' is not editable anymore.
Is it ok?

**Comment by vincent-zurczak** [comment]
I will check this tomorrow with the newly built studio.
However, all the attributes are not strings. How can a user change the type of an attribute through the modeller?

**Comment by philippemerle** [comment]
Use the properties view to set the type of attributes.

**Comment by vincent-zurczak** [comment]
It works correctly now. Tested with **Cloud Designer 0.1.0.201603111301**.
Thanks! :+1:
