### ISSUE TITLE
Registering an OCCI extension results in a file:/... URI

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/ecore#59]
Once you have created an OCCI extension, you may want to reuse it (import it) into another one. Consider the following project...

```
project/
   model/
       ext1.occie
       ext2.occie
```

... where ext2 imports ext1.
Right-clicking ext1 and selecting **Cloud Designer** > **Register OCCI Extension** will allow to reference ext1 in a new OCCI project. But this import statement will look like...

```
import "file:/home/vzurczak/workspaces/occiware/project/model/ext1.occie#/"
```

This is correct, but if the project is then shared through a SCM (e.g. Git), then the resource location will not be valid anymore. Instead, registering a workspace extension should be done with a platform URL. Something like...

```
import "platform:/resource/project/model/ext1.occie#/"
```

**Comment by philippemerle** [comment]
Hi Vincent, you are right.
Resolution of issue https://github.com/occiware/ecore/issues/30 could help.

My ext1.occie contains:
```
extension ext1 : "http://occiware.org/ext1#"
import "http://schemas.ogf.org/occi/core#/"
```
I registered ext1.occie.
My ext2.occie contains
```
extension ext2 : "http://occiware.org/ext2#"
import "http://occiware.org/ext1#/"
```
Could you try this way? Is it right for you?

**Comment by philippemerle** [comment]
Now registering an OCCI extension will store a platform:/resource/... URI.
Vincent : Could you check this? If ok, could we close this issue?

**Comment by vincent-zurczak** [comment]
I cannot check registered extensions use platform URIs.
Given your commit, I assume it does it.

And the reason why I cannot verify it is what you mention in your previous answer.
Imports are performed based on the extension scheme and not on file locations anymore. That's fine for me.

I close this ticket.
