### ISSUE TITLE
 [ OCCIE Modeller ] Action edition bugs #55 

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/ecore#60]
This is almost a twin of #55.
Add a new action to a kind and edit its label.

`test()` will become `test()()`.
`test` will become `test()`. That's correct.
`test( String toto )` will become `test( String toto )()`.

**Comment by philippemerle** [comment]
Hi Vincent,
I commited a correction for this issue.
Now, direct edit allows one to change only the term of the action, i.e., '()' is no more editable.
Is it ok?

**Comment by vincent-zurczak** [comment]
I will check this tomorrow with the newly built studio.
This behavior seems good to me.

Then, I am not enough familiar with OCCI actions, but how could a user specify parameters to its actions? I will take a look at this tomorrow. :smiling_imp:

**Comment by philippemerle** [comment]
Currently, the OCCI Extension designer does not allow one to manage parameters of actions.
This must be done.

**Comment by vincent-zurczak** [comment]
OK. The bug by itself was solved.
Now, we miss a feature: editing action parameters. I will create another issue for this.
