### ISSUE TITLE
[ XText Editor for OCCI extensions ] Validation error with locally referenced extensions

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/ecore#61]
This is a follow-up of #59.
As a reminder, consider the following project...

```
project/
   model/
       ext1.occie
       ext2.occie
```

... where ext2 imports ext1.
When ext2 references ext1 with a platform resource, that is to say...

```
import "platform:/resource/project/model/ext1.occie#/"
```

... the editor rewrites the import as...

```
import "ext1.occie#/"
```

This is valid (relative URL) and the diagram editor has no issue with it.
But the XText editor adds an error on the previous imports (the one about OCCI Core). More exactly, with...

```
extension RoboconfInstances : "http://roboconf.net/instances#"
import "platform:/plugin/org.occiware.clouddesigner.occi/model/Core.occie#/"
import "ext1.occie#/"
```

... there is an error marker on the line of `import "platform:/plugin/org.occiware.clouddesigner.occi/model/Core.occie#/"` with the following message: 

```
The feature 'import' of 'org.occiware.clouddesigner.occi.impl.ExtensionImpl@12ad53a6{platform:/resource/occi-extensions-for-roboconf/model/ext1.occie#/0}'
   contains an unresolved proxy 'org.occiware.clouddesigner.occi.impl.ExtensionImpl@22deaf3b{ext1.occie#/}'
```

There is no error with a file URL.
And I do not see why there would be one with platform URLs.

**Comment by philippemerle** [comment]
Hi Vincent, 
Could you try the solution I proposed for issue https://github.com/occiware/ecore/issues/59?
ext1.occie contains:
```
extension ext1 : "http://occiware.org/ext1#"
import "http://schemas.ogf.org/occi/core#/"
```
I registered ext1.occie.
ext2.occie contains
```
extension ext2 : "http://occiware.org/ext2#"
import "http://occiware.org/ext1#/"
```
Then ext2.occie is fully independent of the location of ext1.occie.
Is it right for you?

**Comment by vincent-zurczak** [comment]
It works for me.
We indeed need to register extensions to import first, but once done, live modifications to these registered extensions work. It means there is no cache of these extensions and this is good.

I close this ticket.
