### ISSUE TITLE
generate xml & textile files with no type or title on eclipse mars

### ISSUE THREAD

**Issue by ilucatero** [occiware/ecore#7]
After running the generator (on eclipse Mars), the files contain the definition for DataTypes, Kinds, etc., but in the attributes the types and titles are not inserted.

*see below eclipse logs:*
!ENTRY org.eclipse.acceleo.engine 2 2 2015-08-18 12:41:44.994
!MESSAGE Undefined argument a.type.instanceClassName of invocation at line 0 in Module generate for block toXMLtype(a.type.instanceClassName). Last recorded value of self was org.occiware.clouddesigner.occi.impl.AttributeImpl@235ebba9 (name: occi.core.summary, mutable: true, required: false, default: null, description: A summarising description of the Resource instance., multiple_values: false). Problem found while generating the file '/occiware/workspace/dev-tools/eclipse/samples/org.occiware.linkeddata/src-gen/xml/core.xml'.
!STACK 0
org.eclipse.acceleo.engine.AcceleoEvaluationException: Undefined argument a.type.instanceClassName of invocation at line 0 in Module generate for block toXMLtype(a.type.instanceClassName). Last recorded value of self was org.occiware.clouddesigner.occi.impl.AttributeImpl@235ebba9 (name: occi.core.summary, mutable: true, required: false, default: null, description: A summarising description of the Resource instance., multiple_values: false). Problem found while generating the file '/occiware/workspace/dev-tools/eclipse/samples/org.occiware.linkeddata/src-gen/xml/core.xml'.
	at generate.attribute(Attribute)(generate.mtl:0)
	at generate.attribute(Attribute)(generate.mtl:64)
	at generate.kind(Kind)(generate.mtl:0)
	at generate.kind(Kind)(generate.mtl:37)
	at generate.kind(Kind)(generate.mtl:31)
	at generate.extension(Extension)(generate.mtl:0)
	at generate.extension(Extension)(generate.mtl:21)
	at generate.extension(Extension)(generate.mtl:13)
	at generate.extension(Extension)(generate.mtl:12)
	at generate.main(Extension)(generate.mtl:0)
	at generate.main(Extension)(generate.mtl:7)
	at generate.main(Extension)(generate.mtl:4)

**Comment by philippemerle** [comment]
Issue corrected by commit https://github.com/occiware/ecore/commit/d4fccab0132384907a9b92bf772a7f73b73ad611
