### ISSUE TITLE
Delete the trash directory

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/ecore#70]
As an open source project using a SCM, having a **trash** directory does not make serious at all.
It should be deleted.

**Comment by wpiers** [comment]
Last commit was 10 month ago, so I don't think it is used anymore.  I deleted it.
It can be easily retrieved in history if this is an issue

**Comment by vincent-zurczak** [comment]
>  It can be easily retrieved in history if this is an issue

100% agree. :smiling_imp:
