### ISSUE TITLE
As of OCCI 1.1 (and 1.2), Kind parent's authorized values are: resource and link

### ISSUE THREAD

**Issue by jeanparpaillon** [occiware/ecore#71]
Ongoing discussion at runtime level: https://github.com/erocci/erocci/issues/36

As of today, there is no general semantic associated to the parent relation of Kind.

In Docker extension, for instance, 'Docker' Kind has parent = "...infrastructure#compute" and add an attribute: 'name'.

A possible correct way of modeling it could be with a mixin applying on compute.

Pro: a user creating a 'compute' resource, backed with Docker system, can create a 'compute' resource the _exact_ same way he creates a virtual machine resource, for instance. If, and if he's aware of the Docker extension, he can specify Docker specific attributes.
The implementation deals with the interoperability, not the user.

Cons: the user needs to specify both categories (compute _and_ docker) if he wants to specify docker specific attributes.

**Comment by philippemerle** [comment]
The OCCI core 1.2 specification section 5.3.3 defines a general semantic of the parent relation of Kind.
in Table 4: "parent Kind 0..1 Immutable Another Kind instance which this Kind has an inheritance
relationship with." -> parent relationship = inheritance relationship
around Line 223: "If type B inherits type A, where A is a sub-type of Entity, the Kind instance of B MUST have its parent attribute set to the Kind instance of A" -> nothing here avoid B has parent = A which has parent = resource which has parent = entity -> so in Docker extension, 'Container' Kind has parent = "...infrastructure#compute" and this seems valid according to OCCI core specification.
Nothing in OCCI limits a kind inheritance graph to 3 levels (entity, resource/link, user defined kinds).

**Comment by philippemerle** [comment]
Modeling Container has a mixin appliable to Compute is an alternative design choice.
But if Container is a mixin then it can be added or removed dynamically!
Then any compute can become a container dynamically, and we can remove the container capability dynamically. No sure that we would like these behaviours.
Defining a Container kind makes us sure that a container instance could never loose it container capability and any compute could not become a container dynamically.

**Comment by jeanparpaillon** [comment]
Ok for the inheritance, see: https://github.com/erocci/erocci/issues/36

Regarding your last comment, both modeling approaches have pro/cons. 
Using mixins have the advantage of a better implementation transparency (and interoperability) to the user. Nothing prevents you from implementing containers behind a 'compute' resource, without any additional mixin.

But, ok, this is just an M2 modelling story...
