### ISSUE TITLE
Ecore file for Docker contains relative URIs

### ISSUE THREAD

**Issue by vincent-zurczak** [occiware/ecore#76]
Consider the [Docker ecore file](https://github.com/occiware/ecore/blob/master/clouddesigner/org.occiware.clouddesigner.occi.docker/model/Docker.ecore).

The file references OCCI Core and Infrastructure models through relative URIs. This is valid when we consider the whole set of plugins. However, users may also use these ecore files as examples and using relative URIs will result in unnecessary errors (e.g. when one copies such a Ecore file into his workspace and opens it with a pre-built OCCIware studio).

Instead, platform URLs should be used (`../../` => `platform:/plugin/`).
Besides, it will help to split the studio into several distributions (for those who want).

There may be other extensions in this Git repository that need a similar update.

**Comment by vincent-zurczak** [comment]
In fact, this is true for almost all the files that import models (odesign file included).

**Comment by fifiant** [comment]
Hi @vincent-zurczak well seen. In fact the Docker generator introduces `../../` inside the docker.ecore file same to docker.odesign file which was created with the same URLs. 

I will reporte it to @philippemerle.

Thank.

**Comment by fifiant** [comment]
It is fixed.
