### ISSUE TITLE
Use Maven to manage libs inside the connectors

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#85]
The idea here is to remove all /lib inside the connectors projects by using maven POM.

**Comment by philippemerle** [comment]
Following is the list of concerned jars:
* org.occiware.clouddesigner.occi.cloud.connector/lib/guava-17.0.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/guice-3.0.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/guice-multibindings-3.0.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/jclouds-1.8.1-jar-with-dependencies.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-cinder-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-common-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-keystone-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-marconi-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-neutron-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-nova-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-nova-ec2-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-swift-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-trove-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/rocoto-6.2.jar
* org.occiware.clouddesigner.occi.cloud.connector/lib/swift-1.8.1.jar
* org.occiware.clouddesigner.occi.cloud.design/lib/guava-17.0.jar TODO need it to be duplicated?
* org.occiware.clouddesigner.occi.cloud.design/lib/jclouds-1.8.1-jar-with-dependencies.jar TODO need it to be duplicated?
* org.occiware.clouddesigner.occi.docker.connector/lib/docker-java-3.0.0-SNAPSHOT-jar-with-dependencies.jar
* org.occiware.clouddesigner.occi.docker.connector/lib/jackson-all-1.7.9.jar
* org.occiware.clouddesigner.occi.docker.connector/lib/jsch-0.1.52.jar
* org.occiware.clouddesigner.occi.docker.design/lib/docker-java-3.0.0-SNAPSHOT-jar-with-dependencies.jar TODO need it to be duplicated?
* org.occiware.clouddesigner.occi.docker.design/lib/jackson-all-1.7.9.jar TODO: need it to be duplicated?
* org.occiware.clouddesigner.occi.hypervisor.connector/lib/commons-io-2.4.jar
* org.occiware.clouddesigner.occi.hypervisor.connector/lib/jaxb-api-2.2.jar
* org.occiware.clouddesigner.occi.hypervisor.connector/lib/jna-4.1.0.jar
* org.occiware.clouddesigner.occi.hypervisor.connector/lib/libvirt-0.1-jar-with-dependencies.jar
* org.occiware.clouddesigner.occi.hypervisor.design/lib/docker-java-1.1.1-SNAPSHOT-jar-with-dependencies.jar TODO is it useful? i.e., Docker jar for hypervisor designer?
* org.occiware.clouddesigner.occi.hypervisor.design/lib/jackson-all-1.7.9.jar TODO is it required?

**Comment by fifiant** [comment]
> Le 21 avr. 2016 à 19:44, philippemerle <notifications@github.com> a écrit :
> 
> Following is the list of concerned jars:
> 
> org.occiware.clouddesigner.occi.cloud.connector/lib/guava-17.0.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/guice-3.0.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/guice-multibindings-3.0.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/jclouds-1.8.1-jar-with-dependencies.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-cinder-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-common-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-keystone-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-marconi-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-neutron-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-nova-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-nova-ec2-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-swift-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/openstack-trove-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/rocoto-6.2.jar
> org.occiware.clouddesigner.occi.cloud.connector/lib/swift-1.8.1.jar
> org.occiware.clouddesigner.occi.cloud.design/lib/guava-17.0.jar TODO need it to be duplicated?
Yes I need. 
> org.occiware.clouddesigner.occi.cloud.design/lib/jclouds-1.8.1-jar-with-dependencies.jar TODO need it to be duplicated?
No.
> org.occiware.clouddesigner.occi.docker.connector/lib/docker-java-3.0.0-SNAPSHOT-jar-with-dependencies.jar
> org.occiware.clouddesigner.occi.docker.connector/lib/jackson-all-1.7.9.jar
> org.occiware.clouddesigner.occi.docker.connector/lib/jsch-0.1.52.jar
> org.occiware.clouddesigner.occi.docker.design/lib/docker-java-3.0.0-SNAPSHOT-jar-with-dependencies.jar TODO need it to be duplicated?
No.
> org.occiware.clouddesigner.occi.docker.design/lib/jackson-all-1.7.9.jar TODO: need it to be duplicated?
No.
> org.occiware.clouddesigner.occi.hypervisor.connector/lib/commons-io-2.4.jar
> org.occiware.clouddesigner.occi.hypervisor.connector/lib/jaxb-api-2.2.jar
> org.occiware.clouddesigner.occi.hypervisor.connector/lib/jna-4.1.0.jar
> org.occiware.clouddesigner.occi.hypervisor.connector/lib/libvirt-0.1-jar-with-dependencies.jar
> org.occiware.clouddesigner.occi.hypervisor.design/lib/docker-java-1.1.1-SNAPSHOT-jar-with-dependencies.jar TODO is it useful? i.e., Docker jar for hypervisor designer?
I was for my tests. I have removed it now.
> org.occiware.clouddesigner.occi.hypervisor.design/lib/jackson-all-1.7.9.jar TODO is it required?
No.

**Comment by fifiant** [comment]
This is done.
