### ISSUE TITLE
Log4J Multiples dependencies

### ISSUE THREAD

**Issue by fifiant** [occiware/ecore#86]
Try to Require-Bundles instead of add multiple Log dependency inside connectors projects.

**Comment by philippemerle** [comment]
Partially fixed by https://github.com/occiware/ecore/commit/5fd051271777080adc6eca302029b124572bb193 and https://github.com/occiware/ecore/commit/06cb1b364846ee36f609376cd3d4b20fdd7cbaa6

**Comment by philippemerle** [comment]
Some logging jars are still present:
* org.occiware.clouddesigner.occi.docker.preference/lib/log4j-1.2.17.jar
* org.occiware.clouddesigner.occi.docker.preference/lib/slf4j-api-1.7.12.jar
* org.occiware.clouddesigner.occi.docker.preference/lib/slf4j-log4j12-1.7.12.jar
* org.occiware.clouddesigner.occi.connector.jocci/lib/slf4j-api-1.7.12.jar

**Comment by fifiant** [comment]
Thank you for our reporting. They were removed.
