### ISSUE TITLE
Java connector project produce an empty ResourceConnector class.

### ISSUE THREAD

**Issue by mehdiAhmed** [occiware/ecore#87]
When I create a `Java connector project` for a valide extension, the produced class `ResourceConnector` is empty.
I Attach my extension to test.
[simulation.zip](https://github.com/occiware/ecore/files/242049/simulation.zip)

**Comment by philippemerle** [comment]
Medhi could you check that the issue is corrected?

**Comment by mehdiAhmed** [comment]
Hi Philippe. It works. Thanks
